# Generated by Timsheng
# DO NOT EDIT THIS FILE DIRECTLY
# -*- encoding: utf-8 -*-


Gem::Specification.new do |s|
  s.name = "rspec_pretty_report"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tim sheng"]
  s.date = "2014-10-15"
  s.description = "A more pretty html report for rspec"
  s.email = "278570038@qq.com"
  s.files = [
    "lib/rspec_pretty_report.rb",
    "resources/bootstrap-3.2.0-dist/css/bootstrap-theme-yeti.min.css",
    "resources/bootstrap-3.2.0-dist/css/bootstrap.min.css",
    "resources/bootstrap-3.2.0-dist/fonts/glyphicons-halflings-regular.eot",
    "resources/bootstrap-3.2.0-dist/fonts/glyphicons-halflings-regular.svg",
    "resources/bootstrap-3.2.0-dist/fonts/glyphicons-halflings-regular.ttf",
    "resources/bootstrap-3.2.0-dist/fonts/glyphicons-halflings-regular.woff",
    "resources/bootstrap-3.2.0-dist/js/bootstrap.min.js",
    "resources/jquery-1.11.1.min.js",
    "resources/jscharts.js",
    "rspec_pretty_report.gemspec",
    "spec/penders_spec.rb",
    "spec/rspec_pretty_report_spec.rb",
    "spec/test2_spec.rb",
    "templates/overview.erb",
    "templates/report.erb"
  ]
  s.homepage = "http://github.com/timsheng/rspec_pretty_report"
  s.rubygems_version = "2.2.2"
  s.summary = "Rspec custom formatter to generate pretty html results"
end

